name: hiddify
description: Android Multi Protocol Proxy Frontend.
publish_to: "none"
version: 4.1.2+40102

environment:
  sdk: ^3.13.4
  flutter: ^3.47.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  slang: ^4.19.2
  slang_flutter: ^4.19.0
  fpdart: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  hooks_riverpod: ^3.4.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^4.0.7
  rxdart: ^0.28.0
  drift: ^2.35.1
  drift_flutter: ^0.3.1
  shared_preferences: ^2.5.2
  dio: ^5.4.1
  ffi: ^2.1.2
  path_provider: ^2.1.1
  mobile_scanner: ^7.2.0
  flutter_native_splash: ^2.3.10
  share_plus: ^13.3.1
  package_info_plus: ^10.2.2
  url_launcher: ^6.2.5
  sentry_flutter: 9.30.1
  sentry_dart_plugin: ^3.4.0
  path: ^1.9.0
  loggy: ^2.0.3
  meta: ^1.15.0
  dartx: ^1.2.0
  uuid: ^4.3.3
  tint: ^2.0.1
  accessibility_tools: ^3.0.0
  neat_periodic_task: ^2.0.1
  go_router: ^18.0.2
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  sliver_tools: ^0.2.12
  font_awesome_flutter: ^11.0.0
  upgrader: ^13.7.0
  toastification: ^3.2.0
  version: ^3.0.2
  qr_flutter: ^4.1.0
  flutter_displaymode: ^0.7.0
  dio_smart_retry: ^7.0.1
  dart_mappable: ^4.10.0
  fluentui_system_icons: ^1.1.229
  json_path: ^0.9.0
  in_app_review: ^2.0.10
  circle_flags:
    git: https://github.com/hiddify-com/flutter_circle_flags.git
  fixnum: ^1.1.0
  protobuf: ^5.0.0
  grpc: ^4.0.1
  dynamic_color: ^1.9.0
  flutter_typeahead: ^6.0.0
  simple_icons: ^16.23.0
  basic_utils: ^5.7.0
  text_scroll: ^0.2.0
  flutter_markdown_plus: ^1.0.6
  file_picker: ^13.1.0
  installed_apps:
    git: https://github.com/VB10/installed_apps
  recase: ^4.1.0
  app_links: ^7.2.1
  humanizer: ^3.0.1

dev_dependencies:
  flag_builder:
    path: tool/flag_builder_compat
  lint: ^2.14.0
  build_runner: ^2.16.1
  json_serializable: ^6.14.1
  freezed: ^4.0.2
  riverpod_generator: ^4.0.9
  drift_dev: ^2.35.1
  flutter_gen_runner: ^5.15.0
  dart_mappable_builder: ^4.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/connect_norouz.PNG
    - assets/images/disconnect_norouz.PNG
    - assets/images/world_map.png
    - assets/images/source/ic_launcher_border.png

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf
    - family: Emoji
      fonts:
        - asset: assets/fonts/Emoji.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/source/ic_launcher_splash.png
  android_gravity: center
  android_12:
    color: "#ffffff"
    image: assets/images/source/ic_launcher_foreground.png

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  log_level: info
  ignore_missing: true
