org.gradle.jvmargs=-Xmx4048m -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.builtInKotlin=false
android.newDsl=false

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
