name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - fixerror

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: write
    if: "${{ !contains(github.event.head_commit.message || '', 'release: version') }}"
    with:
      upload-artifact: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev') }}
